# Generated by Django 5.2.8 on 2025-11-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_options_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='base_color',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='design_image_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='base_color',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='design_image_url',
            field=models.TextField(default=''),
        ),
    ]
