# Generated by Django 5.2.8 on 2025-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(help_text='Imgur link for this design template')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
