# Generated by Django 5.2.8 on 2025-12-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_designtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignTemplate',
        ),
        migrations.AddField(
            model_name='product',
            name='template_image_url',
            field=models.URLField(blank=True, help_text='Optional Imgur link for the design template preview', null=True),
        ),
    ]
